; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=TP_CG
AppVersion=1.0
DefaultDirName={autopf}\TP CG
DefaultGroupName=TP CG
OutputDir=installer
OutputBaseFilename=TP_CG_Setup
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Files]
Source: "dist\TP_CG\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\TP CG"; Filename: "{app}\TP_CG.exe"
Name: "{autodesktop}\CG Algorithms Lab"; Filename: "{app}\TP_CG.exe"

[Run]
Filename: "{app}\TP_CG.exe"; Description: "Abrir CG Algorithms Lab"; Flags: nowait postinstall skipifsilent

